import java.util.ArrayList;


/**
 * <h1>Truck</h1> Represents a Truck
 *
 * @author (jacks668, David Jackson), (morri417, Mahira Morris)
 *
 * @version 12/9/18
 */
public class Truck extends Vehicle {

    private final double gasRate = 1.66;

    /**
     * Default Constructor
     */
    //============================================================================
    //
    public Truck() {
        super();
    }
    //============================================================================

    /**
     * Constructor
     * 
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    //
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }
    
    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        double revenue = 0.0;
        for (Package pkg : getPackages()) {
            revenue += pkg.getPrice();
        }
        return revenue - (getRange() - 1) * this.gasRate;
    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     * 
     * @return Truck Report
     */
    @Override
    public String report() {
        String report = "==========Truck Report==========\n" +
                "License Plate No.: " + getLicensePlate() + "\n" +
                "Destination: " + getZipDest() + "\n" +
                String.format("Weight Load: %.2f/%.2f\n", getCurrentWeight(), getMaxWeight()) +
                String.format("Net Profit: $%.2f\n", this.getProfit()) +
                "=====Shipping Labels=====\n";
        for (Package pkg : getPackages()) {
            report += pkg.shippingLabel();
        }
        report += "==============================\n";
        return report;
    }



}